baseURL  = "https://git-forseti.github.io/blog/"
theme = "bleak-forseti"
languageCode = "en-us"
buildDrafts = false
publishdir = "public"
canonifyURLs = true
title = "Blog da Forseti"


[params]
cover = "images/php-code.jpg"
Subtitle = "Equipe da Forseti passando para frente o conhecimento"
description = "Compartilhando conhecimento"
dateform = "2 Jan, 2006"
dateformfull = "2 Mon Jan 2006 15:04:05 MST"
logo = "/images/forseti.jpg"
lang = "pt-br"
github = "https://github.com/git-forseti/"
email = "forseti@forseti.com.br"
linkedin = ""
twitter = ""

googleAnalyticsUserID = "UA-87718763-2"
domainVerification = "BwRbXye33xQZRZzKlpn8_SZ0-rpspRIU852dQTt7QkA"
disqus = "blogforseti"

[params.author]
    userName = "Forseti Tecnologia e Comunicação"
